### ISSUE TITLE
 Error: Unsupported SQL_XXX type returned for SQL_LONGVARCHAR datatype

### ISSUE THREAD

**Issue by orr721** [metaeducation/rebol-odbc#9]
```
C:\TEMP>r3-a9c9ed0.exe
Rebol 3 (Ren-C branch) [version: 2.102.0.3.1 build: 29-Oct-2019/3:18:46+0:00]
...
>> p: open odbc://testexpcs
== #[port! [...] [...]]

>> c: first p
== #[port! [...] [...]]

>> odbc-execute c "select Záver from [Sheet0$]"
== [Záver]

>> copy c
** Error: Unsupported SQL_XXX type returned from query
** Where: copy-odbc _ copy console
** Near: [
    copy-odbc port/locals part ~~]
** Line: 113

>> insert c ['columns]
== [TABLE_CAT TABLE_SCHEM TABLE_NAME COLUMN_NAME DATA_TYPE TYPE_NAME COLUMN_SIZE BUFFER_LENGTH DECIMAL_DIGITS NUM_PREC_RADIX NULLABLE REMARKS COLUMN_DEF SQL_DATA_TYPE SQL_DATETIME_SUB CHAR_OCTET_LENGTH ORDINAL_POSITION IS_NULLABLE ORDINAL] 

>> x: copy c
...
>> x/10
== ["C:\TEMP\expcs.xlsx" _ "Sheet0$" "Záver" -1 _ 1073741824 1073741824 _ _ 1 _ _ -1 _ 1073741824 10 "YES" 10]
```

It looks like the "-1" LONGVARCHAR datatype is not supported by the current rebol-odbc.

A similar problem was fixed in 2017 in the [e6718d6 commit](https://github.com/metaeducation/ren-c/commit/e6718d6e36fdc11dfaba586dd4920d906cce0b40). The relevant discussion is in [the forum here](https://forum.rebol.info/t/obdc-excel-and-memory-allocation-problems/280), see especially [this post](https://forum.rebol.info/t/obdc-excel-and-memory-allocation-problems/280/15?u=orr721).

Please don't forget about the 32K size cap of the value. Thank you.

**Comment by hostilefork** [comment]
My build asserts due to that last patch not being applied to LONGVARCHAR (are you not using a debug build?)

This made LONGVARCHAR work for me:

https://github.com/metaeducation/ren-c/commit/12d29bb4f778be2dbda39731100e5e0c087f34ab

**Comment by orr721** [comment]
sorry, you are right, the debug build error was:
```
C:\TEMP>r3-a9c9ed0-debug-cpp.exe
...
>>copy c
Assertion failed!                                                                                              
                                                                                                               
Program: C:\TEMP\r3-a9c9ed0-debug-cpp.exe                                                                      
File: ../extensions/odbc/mod-odbc.c, Line 1423                                                                 
                                                                                                               
Expression: !"UCS-2 should have requested SQL_C_WCHAR"                                                         
                                                                                                               
C:\TEMP>
```
I have (wrongly) assumed the non-debug error to be more descriptive. missing datatype name, etc. oh well, I am not a C programmer I have told you.

> This made LONGVARCHAR work for me:
> 
> [metaeducation/ren-c@12d29bb](https://github.com/metaeducation/ren-c/commit/12d29bb4f778be2dbda39731100e5e0c087f34ab)

yes indeed. This is my new favorite rebol/r3-renc build. Thanks a lot.

**Comment by hostilefork** [comment]
> I have (wrongly) assumed the non-debug error to be more descriptive.

Ideally non-debug builds don't crash if an internal mistake would not cause data loss.  If you fear a mistake would cause data loss, you force a crash.  (e.g. "Blue screen of death" `*`)

> This is my new favorite rebol/r3-renc build

Good.  :-)  The more you can participate...trying new things, the better.  If you can share what you are working on with GitHub, that would provide opportunities for discussion.

The function compositions (ADAPT, SPECIALIZE, ENCLOSE, CHAIN) are very powerful--you can think of new functions as being just variations of existing ones.  A good example here is building COLLECT variants, it's worth looking at:

https://forum.rebol.info/t/collect-lines-an-adaptation-story/945

How NULL works as the replacement for NONE!, that cannot be put in a block, is foundational.  I'm interested to see how well people are understanding it / appreciating it / using it.  So if you can chime in on some of the debates, that would be good.  An example there:

https://forum.rebol.info/t/regarding-mutual-exclusivity-of-then-and-else/1174

---

*`*`: [Our blue screen of death is called panic()](https://github.com/metaeducation/ren-c/blob/12d29bb4f778be2dbda39731100e5e0c087f34ab/src/core/d-crash.c#L39).  The functionality is actually exposed as a [native called PANIC](https://github.com/metaeducation/ren-c/blob/12d29bb4f778be2dbda39731100e5e0c087f34ab/src/core/d-crash.c#L196) and another called [PANIC-VALUE](https://github.com/metaeducation/ren-c/blob/12d29bb4f778be2dbda39731100e5e0c087f34ab/src/core/d-crash.c#L236) if there's reason to invoke it from usermode.*
